REPORT zag_test_comment.

SELECTION-SCREEN:
  BEGIN OF BLOCK b1 WITH FRAME,
    COMMENT /1(55) c_docu FOR FIELD p_docu.
PARAMETERS:
  p_docu TYPE c LENGTH 20.
SELECTION-SCREEN:
  END OF BLOCK b1.

INITIALIZATION.

  c_docu = 'Show Docs'.
